services:
  
  # apps
  
  app:
    container_name: tradelens-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6502:6501"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=sql;Port=5432;Database=tradelens-db;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://*:6501
    depends_on:
      - sql
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: fluent-bit:24224
  
  # backing services
  
  sql:
    image: postgres:17.2-alpine3.21
    container_name: tradelens-db
    restart: always
    environment:
      - POSTGRES_DB=tradelens-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - sql-data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - ConnectionStrings__Redis=redis
  
  # observability
  
  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.2
    platform: linux/amd64
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
  #    volumes:
  #      - ./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
  #      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
  #      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini
  
  loki:
    container_name: loki
    image: grafana/loki:3.4
    platform: linux/amd64
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"
  
  fluent-bit:
    container_name: fluent-bit
    image: grafana/fluent-bit-plugin-loki:3.4.2-amd64
    platform: linux/amd64
    ports:
      - "24224:24224"
    # url to forward log messages
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf


volumes:
  redis-data:
  sql-data:
