services:
  sql:
    image: postgres:17.2-alpine3.21
    container_name: tradelens-db
    restart: always
    environment:
      - POSTGRES_DB=tradelens-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - sql-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - ConnectionStrings__Redis=redis

  app:
    container_name: tradelens-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6502:6501"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=sql;Port=5432;Database=tradelens-db;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://*:6501
    depends_on:
      - sql

volumes:
  redis-data:
  sql-data:
