"""added the stocks model

Revision ID: 47734170c51a
Revises: 57e0a3e04490
Create Date: 2024-02-28 12:48:57.041034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47734170c51a'
down_revision = '57e0a3e04490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('institutional_info', sa.Text(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_ticker_symbol'), ['ticker_symbol'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_ticker_symbol'))
        batch_op.drop_index(batch_op.f('ix_stocks_company_name'))

    op.drop_table('stocks')
    # ### end Alembic commands ###
