server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

## local machine logs
#scrape_configs:
#  - job_name: system
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: varlogs
#          __path__: /var/log/*log

## docker logs
#scrape_configs:
#  - job_name: docker
#    pipeline_stages:
#      - docker: {}
#    static_configs:
#      - labels:
#          job: docker
#          __path__: /var/lib/docker/containers/*/*-json.log

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'     