name: Feature Request
description: Suggest a feature for TradeLens
labels: kind/feature
title: ''
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Suggest a feature
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why would you like to see this?
    validations:
      required: true
