"""empty message

Revision ID: 465d94e08da1
Revises: 53946a4c6705
Create Date: 2024-02-14 12:09:59.645750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465d94e08da1'
down_revision = '53946a4c6705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('number_of_tutes',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('percentage_tutes',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('percentage_insiders',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('percentage_insiders',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('percentage_tutes',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('number_of_tutes',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
