"""empty message

Revision ID: 704d8ef42937
Revises: 465d94e08da1
Create Date: 2024-02-14 17:02:48.957312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704d8ef42937'
down_revision = '465d94e08da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institutional_info', sa.Text(), nullable=True))
        batch_op.drop_column('number_of_tutes')
        batch_op.drop_column('percentage_tutes')
        batch_op.drop_column('percentage_insiders')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage_insiders', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('percentage_tutes', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('number_of_tutes', sa.FLOAT(), nullable=True))
        batch_op.drop_column('institutional_info')

    # ### end Alembic commands ###
