"""empty message

Revision ID: 9ddd501513c7
Revises: 792b751f9412
Create Date: 2024-02-11 18:16:22.479073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddd501513c7'
down_revision = '792b751f9412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('volume')
        batch_op.drop_column('close')
        batch_op.drop_column('low')
        batch_op.drop_column('high')
        batch_op.drop_column('open')

    # ### end Alembic commands ###
