"""about me, last seen, date joined columns in User model

Revision ID: d0744e0e65cd
Revises: 39df33dc3b17
Create Date: 2024-02-25 16:27:18.996109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0744e0e65cd'
down_revision = '39df33dc3b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_date_joined'), ['date_joined'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_date_joined'))
        batch_op.drop_column('date_joined')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
