name: Ping API Endpoint to Keep App Active

on:
  schedule:
    - cron: '*/13 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping App Active Endpoint
        run: |
          curl --silent --fail --show-error https://tradelens.azurewebsites.net/ping
